# Generated by Django 4.0.3 on 2022-03-06 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(default='default.jpg', upload_to=''),
        ),
    ]
