# Generated by Django 4.0.1 on 2022-02-09 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='image',
            field=models.ImageField(default='default_profile.jpg', upload_to=''),
        ),
    ]
