# Generated by Django 4.0.1 on 2022-01-19 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='isnb',
            new_name='isbn',
        ),
    ]
