# Generated by Django 4.0.1 on 2022-01-19 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_rename_isnb_book_isbn'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookreview',
            name='comment',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
